sbatch csh_allo_d_stanage_array_no_rerun.sh
sbatch csh_allo_d_stanage_array_no_rerun_no_disconnected.sh
sbatch csh_allo_d_stanage_array_no_rerun_short.sh
sbatch csh_non_allo_d_stanage_array_no_rerun.sh
sbatch csh_allo_d_stanage_array_fixed.sh
