---
title: "Vasseur \& Fox (2007) replication"
author: Alain Danet
date: \today
output:
  bookdown::pdf_document2:
    fig_caption: true
    keep_tex: true
    toc: true
    fontsize: 12pt
    geometry: margin=2cm
    number_sections: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  collapse = TRUE,
  comment = "#>",
  #fig.dim = c(7, 7),
  fig.fullwidth = TRUE,
  fig.show = "hold",
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  results = TRUE,
  fig.path="figures/"
)
```

```{r, results = FALSE}
library(tidyverse)
library(magrittr)
library(cowplot)
library(here)
require(rgl)
options(rgl.printRglwidget = TRUE)

mytheme <- theme_cowplot(font_size = 12) +
  background_grid() +
  theme(legend.position = "bottom")


theme_set(mytheme)
options(knitr.table.format = "latex")
```

# Some simulations with stochasticity

```{r}
sim <- read_csv(here("use_case", "vasseur_fox_sim_ts_ex.csv")) %>%
  pivot_longer(c(resource:pred), names_to = "species", values_to = "bm") %>%
  mutate(species = str_replace_all(species, c(
        "pred" = "Predator",
        "cons1" = "Consumer 1",
        "cons2" = "Consumer 2",
        "resource" = "Resource"
        )))

sim0 <- sim %>%
  filter(sigma == 0)
unique(sim$sigma)
unique(sim$rho)
```

```{r}
p0 <- sim %>%
  filter(sigma == 0) %>%
  ggplot(aes(x = time, y = bm, color = species)) +
  geom_line()
save_plot(
  filename = here("use_case", "int_mccann_brose", "figures", "mccann_sim.png"),
  p0)
p_stoch <- sim %>%
  filter(sigma == 0.3, rho == 0.0) %>%
  ggplot(aes(x = time, y = bm, color = species)) +
  geom_line()
p_stoch_rho <- sim %>%
  filter(sigma == 0.3, rho == 1) %>%
  ggplot(aes(x = time, y = bm, color = species)) +
  geom_line()
```

```{r}
```




# Reproduce Vasseur & Fox

```{r}
data <- read_csv(here("res", "vasseur_fox_res.csv"))
colnames(data)[1:2] <- c("rho", "sigma")
```

```{r}
avg  <- data %>%
  group_by(sigma, rho) %>%
  summarise(across(everything(), mean))
```


```{r}
surface3d(avg$rho, avg$stab_pred, avg$sigma)
map(c("rho", "stab_pred", ))
```

```{r}
cons_sync <- avg %>%
  ggplot(aes(rho, sigma, z = sync_cons)) +
  geom_contour_filled() +
  labs(x = "Environmental correlation", y = "Fluctuation strength") +
  labs(fill = "Consumer synchrony")

pred_stab <- ggplot(avg, aes(rho, sigma, z = stab_pred)) +
  geom_contour_filled() +
  labs(x = "Environmental correlation", y = "Fluctuation strength") +
  labs(fill = "Predator stability")

cons1_stab <- avg %>%
  ggplot(aes(rho, sigma, z = stab_cons1)) +
  geom_contour_filled() +
  labs(x = "Environmental correlation", y = "Fluctuation strength") +
  labs(fill = "Consumer 1 stability")

cons2_stab <- avg %>%
  ggplot(aes(rho, sigma, z = stab_cons2)) +
  geom_contour_filled() +
  labs(x = "Environmental correlation", y = "Fluctuation strength") +
  labs(fill = "Consumer 2 stability")
```

```{r}
pp <- plot_grid(
  cons_sync, pred_stab, cons1_stab, cons2_stab,
  labels = "auto")
save_plot(
  filename = here("res", "vasseurfox2007fig2.pdf"),
  pp, ncol = 2, nrow = 2)
```



